id: PB4D8244C
initial_creation_type: ocr
source_metadata:
  volumes:
    7bbb8fe3a09949fda746220e11b5dbb5:
      base_file: v017.txt
      image_group_id: I1PD95862
      title: སྒྲོན་མ་གསལ་བར་བྱེད་པའི་དགོངས་པ་རབ་གསལ་ཞེས་བྱ་བ་བཤད་པའི་ཊཱི་ཀཱ།
      total_pages: 1158
      volume_number: 17
vol2fn:
  v017: v017.txt
